vich_uploader:
    db_driver: orm

    mappings:
        produit:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        etape:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        conseiller:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

